---
 - name: fist playbook
   hosts: all
   becomes: true
   tasks:
      - name: Install httpd software
        yum:
          - name: httpd
            state: latest
        service: 
          name: httpd
          service: started
    

