---
  - name: loop playbook
    hosts: dev
    become: true
    tasks:
      - name: Instlall multiple softwares
        yum: 
          name: "{{item}}"
          state: present
        with_items:
          - git
          - tree
